services:
  - type: web
    name: aoi-v3-landing
    runtime: node
    rootDir: landing
    plan: free
    autoDeploy: true
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.13.1
      - key: BACKEND_API_URL
        sync: false
      - key: FRONTEND_APP_URL
        sync: false
      - key: DISCORD_REDIRECT_URI
        sync: false
      - key: NEXT_PUBLIC_DASHBOARD_URL
        sync: false
